version: '2'
services:
  devhub:
    build: devhub
    ports:
     - "3000:3000"
    depends_on:
     - "mongo_db"
    links:
     - "mongo_db"
    environment:
      MONGOLAB_URI: "mongodb://mongo_db:27017/devhub_db"
      MONGODB_IP_ADDR: mongo_db
    command: [ "/root/wait-for-mongo.sh", "--", "node", "app.js", "-p", "3000", "-d", "devhub_db", "-t", "${TITLE}" ]
  mongo_db:
    image: "mongo"
    expose:
     - "27017"
